name: CI Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar
        run: mvn clean package

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t buifhong/baitap_dock .

      - name: Push image
        run: docker push buifhong/baitap_dock

 
      - name: Trigger Deploy Webhook
        run: curl -X GET ${{ secrets.DEPLOY_URL }}
